{% set name = "pemja" %}
{% set version = "0.5.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pemja-{{ version }}.tar.gz
  sha256: 44b17e48646e66d428ddfeda5214c132aa6d4569e795fc95a1cee5d76330f87d

build:
  skip: true  # [win or py<3.8]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - openjdk
  host:
    - python
    - packaging >=20.5
    - setuptools
    - wheel
    - pip
  run:
    - python
    - find-libpython

test:
  imports:
    - pemja
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/alibaba/pemja
  summary: PemJa is an open source cross language call framework based on FFI. It aims to provide a high-performance framework of calling between different languages.
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://github.com/alibaba/pemja

extra:
  recipe-maintainers:
    - gforsyth
    - deepyaman
