{% set name = "pemja" %}
{% set version = "0.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pemja-{{ version }}.tar.gz
  sha256: 88ffcd5427725e12b10c8740e0b061087f5d1a66abef9cf932e3d4821b4033f9

build:
  skip: true  # [win or py<3.8]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - openjdk
  host:
    - python
    - packaging >=20.5
    - setuptools
    - wheel
    - pip
  run:
    - python
    - find-libpython

test:
  imports:
    - pemja
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/alibaba/pemja
  summary: PemJa is an open source cross language call framework based on FFI. It aims to provide a high-performance framework of calling between different languages.
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://github.com/alibaba/pemja

extra:
  recipe-maintainers:
    - gforsyth
    - deepyaman
