{% set name = "pemja" %}
{% set version = "0.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pemja-{{ version }}.tar.gz
  sha256: 38b0466ba48822cd9fa65bf8465c45474bf3f048d6458388e0bf895904258e8c

build:
  skip: true  # [win or py<3.8]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - openjdk
  host:
    - python
    - packaging >=20.5
    - setuptools
    - wheel
    - pip
  run:
    - python
    - find-libpython

test:
  imports:
    - pemja
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/alibaba/pemja
  summary: PemJa is an open source cross language call framework based on FFI. It aims to provide a high-performance framework of calling between different languages.
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://github.com/alibaba/pemja

extra:
  recipe-maintainers:
    - gforsyth
    - HuangXingBo
    - deepyaman
